import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsOfServicePage() {
  return (
    <div className="max-w-content mx-auto px-6 py-16 sm:py-24">
      {/* Header */}
      <div className="mb-16 pb-16 border-b border-gray-100">
        <p className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
          Legal
        </p>
        <h1 className="text-4xl sm:text-5xl font-light text-black leading-editorial mb-4">
          Terms of Service
        </h1>
        <p className="text-sm text-gray-500">Last updated: March 2026</p>
      </div>

      <div className="space-y-12 max-w-prose">
        {/* 1. Acceptance */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
            1. Acceptance of terms
          </h2>
          <div className="space-y-4 text-sm text-gray-700 leading-relaxed">
            <p>
              By accessing or using Laozi AI (the &ldquo;Service&rdquo;), you
              agree to be bound by these Terms of Service. If you do not agree,
              do not use the Service.
            </p>
            <p>
              These terms apply to all users, including those who access the
              Service without creating an account and those who create accounts
              and use paid or free features.
            </p>
            <p>
              We reserve the right to modify these terms at any time. Continued
              use of the Service following notice of changes constitutes
              acceptance of the revised terms. We will notify registered users
              of material changes via email.
            </p>
          </div>
        </section>

        {/* 2. Service description */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
            2. Service description
          </h2>
          <div className="space-y-4 text-sm text-gray-700 leading-relaxed">
            <p>
              Laozi AI is a reflective intelligence interface that provides
              structured reasoning analysis across five modes: Quiet Mirror,
              Strategic Governance, Conflict Dissolution, Personal Discipline,
              and Institutional Judgment.
            </p>
            <p>
              <strong className="font-semibold text-black">
                The Service is not a substitute for professional advice.
              </strong>{" "}
              Outputs generated by Laozi AI are for reflective and analytical
              purposes only. They do not constitute medical advice, legal
              advice, financial advice, psychological counseling, or any other
              form of professional service.
            </p>
            <p>
              You must apply your own judgment before acting on any analysis
              produced by the Service. Consult qualified professionals for
              decisions in domains requiring professional expertise.
            </p>
            <p>
              The Service uses third-party AI providers to generate responses.
              We do not guarantee the accuracy, completeness, or fitness for any
              particular purpose of any output.
            </p>
          </div>
        </section>

        {/* 3. User responsibilities */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
            3. User responsibilities
          </h2>
          <div className="space-y-4 text-sm text-gray-700 leading-relaxed">
            <p>
              You are responsible for all activity that occurs under your
              account. You must:
            </p>
            <ul className="space-y-2">
              {[
                "Provide accurate information when creating your account.",
                "Maintain the security of your account credentials.",
                "Notify us immediately of any unauthorized access to your account.",
                "Use the Service only for lawful purposes and in accordance with these terms.",
                "Be at least 18 years of age to use the Service.",
              ].map((item) => (
                <li key={item} className="flex items-start gap-3">
                  <span className="text-gray-300 shrink-0 mt-0.5">
                    &mdash;
                  </span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* 4. Prohibited uses */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
            4. Prohibited uses
          </h2>
          <div className="space-y-4 text-sm text-gray-700 leading-relaxed">
            <p>You may not use the Service to:</p>
            <ul className="space-y-2">
              {[
                "Harass, threaten, or harm any person.",
                "Generate content designed to facilitate fraud, deception, or illegal activity.",
                "Produce content that is defamatory, obscene, or violates the rights of others.",
                "Attempt to manipulate, circumvent, or abuse the AI systems underlying the Service.",
                "Harvest or scrape data from the Service in an automated or bulk manner.",
                "Impersonate any person or entity.",
                "Violate any applicable local, national, or international law or regulation.",
                "Use the Service in any manner that could damage, disable, or impair the Service or its infrastructure.",
                "Attempt to gain unauthorized access to any part of the Service.",
                "Generate content that targets or endangers minors.",
              ].map((item) => (
                <li key={item} className="flex items-start gap-3">
                  <span className="text-gray-300 shrink-0 mt-0.5">
                    &mdash;
                  </span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              We reserve the right to terminate accounts engaged in prohibited
              activities without notice and to report illegal activity to
              relevant authorities.
            </p>
          </div>
        </section>

        {/* 5. Intellectual property */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
            5. Intellectual property
          </h2>
          <div className="space-y-4 text-sm text-gray-700 leading-relaxed">
            <p>
              The Service, including its design, software, mode frameworks, and
              underlying systems, is owned by or licensed to Laozi AI. Nothing
              in these terms grants you any right to use our trademarks, trade
              names, or other proprietary marks.
            </p>
            <p>
              You retain ownership of the content you provide as inputs to the
              Service. By submitting content, you grant us a limited,
              non-exclusive license to use that content as necessary to operate
              the Service.
            </p>
            <p>
              Outputs generated by the Service are provided for your use. We do
              not claim ownership of outputs generated in response to your
              inputs, but we do not warrant that outputs are original, free from
              third-party rights claims, or suitable for commercial use.
            </p>
          </div>
        </section>

        {/* 6. Limitation of liability */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
            6. Limitation of liability
          </h2>
          <div className="space-y-4 text-sm text-gray-700 leading-relaxed">
            <p>
              To the maximum extent permitted by applicable law, Laozi AI and
              its operators shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages arising from your use
              of, or inability to use, the Service.
            </p>
            <p>
              In no event shall our total liability to you for all claims
              arising from your use of the Service exceed the amount you paid
              to us in the twelve months preceding the claim, or $10, whichever
              is greater.
            </p>
            <p>
              We do not warrant that the Service will be uninterrupted,
              error-free, or that outputs will be accurate, complete, or
              suitable for any particular purpose. The Service is provided
              &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
              warranty of any kind.
            </p>
          </div>
        </section>

        {/* 7. Indemnification */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
            7. Indemnification
          </h2>
          <div className="space-y-4 text-sm text-gray-700 leading-relaxed">
            <p>
              You agree to indemnify, defend, and hold harmless Laozi AI and
              its operators from any claims, damages, losses, liabilities, and
              expenses (including reasonable legal fees) arising from your use
              of the Service, your violation of these terms, or your violation
              of any rights of a third party.
            </p>
          </div>
        </section>

        {/* 8. Termination */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
            8. Termination
          </h2>
          <div className="space-y-4 text-sm text-gray-700 leading-relaxed">
            <p>
              We may terminate or suspend your account at any time, with or
              without notice, for conduct that we determine violates these terms
              or is harmful to other users, us, third parties, or the integrity
              of the Service.
            </p>
            <p>
              You may terminate your account at any time by contacting us. Upon
              termination, your right to use the Service ceases. Provisions of
              these terms that by their nature should survive termination will
              survive.
            </p>
          </div>
        </section>

        {/* 9. Governing law */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
            9. Governing law
          </h2>
          <div className="space-y-4 text-sm text-gray-700 leading-relaxed">
            <p>
              These terms shall be governed by and construed in accordance with
              the laws of [Jurisdiction], without regard to its conflict of law
              provisions. Any dispute arising under these terms shall be subject
              to the exclusive jurisdiction of the courts of [Jurisdiction].
            </p>
          </div>
        </section>

        {/* 10. Contact */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
            10. Contact
          </h2>
          <div className="space-y-4 text-sm text-gray-700 leading-relaxed">
            <p>
              For questions about these terms, contact us through the{" "}
              <Link
                href="/contact"
                className="text-black underline underline-offset-4 hover:text-gray-600 transition-colors"
              >
                contact page
              </Link>
              .
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
